/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SensiLog API
 * VALORANT感度・設定管理API
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  Error,
  GetMatchData200,
  GetMatchDataParams,
  PostMatchDataSync202,
  UnauthorizedResponse,
} from ".././schemas";
import getMatchDataMutator from ".././mutator";
import postMatchDataSyncMutator from ".././mutator";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary 試合データ取得
 */
export const getMatchData = (
  params?: GetMatchDataParams,
  options?: SecondParameter<typeof getMatchDataMutator>,
  signal?: AbortSignal,
) => {
  return getMatchDataMutator<GetMatchData200>(
    { url: `/match-data`, method: "GET", params, signal },
    options,
  );
};

export const getGetMatchDataQueryKey = (params?: GetMatchDataParams) => {
  return [`/match-data`, ...(params ? [params] : [])] as const;
};

export const getGetMatchDataInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getMatchData>>,
  TError = UnauthorizedResponse,
>(
  params?: GetMatchDataParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getMatchData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMatchDataQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatchData>>> = ({
    signal,
  }) => getMatchData(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getMatchData>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMatchDataInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMatchData>>
>;
export type GetMatchDataInfiniteQueryError = UnauthorizedResponse;

/**
 * @summary 試合データ取得
 */
export const useGetMatchDataInfinite = <
  TData = Awaited<ReturnType<typeof getMatchData>>,
  TError = UnauthorizedResponse,
>(
  params?: GetMatchDataParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getMatchData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataMutator>;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMatchDataInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetMatchDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getMatchData>>,
  TError = UnauthorizedResponse,
>(
  params?: GetMatchDataParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMatchData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMatchDataQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatchData>>> = ({
    signal,
  }) => getMatchData(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMatchData>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMatchDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMatchData>>
>;
export type GetMatchDataQueryError = UnauthorizedResponse;

/**
 * @summary 試合データ取得
 */
export const useGetMatchData = <
  TData = Awaited<ReturnType<typeof getMatchData>>,
  TError = UnauthorizedResponse,
>(
  params?: GetMatchDataParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMatchData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataMutator>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMatchDataQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary 試合データ手動同期
 */
export const postMatchDataSync = (
  options?: SecondParameter<typeof postMatchDataSyncMutator>,
) => {
  return postMatchDataSyncMutator<PostMatchDataSync202>(
    { url: `/match-data/sync`, method: "POST" },
    options,
  );
};

export const getPostMatchDataSyncMutationOptions = <
  TError = UnauthorizedResponse | Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMatchDataSync>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof postMatchDataSyncMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMatchDataSync>>,
  TError,
  void,
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMatchDataSync>>,
    void
  > = () => {
    return postMatchDataSync(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostMatchDataSyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMatchDataSync>>
>;

export type PostMatchDataSyncMutationError = UnauthorizedResponse | Error;

/**
 * @summary 試合データ手動同期
 */
export const usePostMatchDataSync = <
  TError = UnauthorizedResponse | Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMatchDataSync>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof postMatchDataSyncMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postMatchDataSync>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostMatchDataSyncMutationOptions(options);

  return useMutation(mutationOptions);
};
