/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SensiLog API
 * VALORANT感度・設定管理API
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  ComparisonResult,
  GetAnalyticsPerformance200,
  GetAnalyticsPerformanceParams,
  PostAnalyticsComparisonBody,
} from ".././schemas";
import getAnalyticsPerformanceMutator from ".././mutator";
import postAnalyticsComparisonMutator from ".././mutator";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary パフォーマンス分析データ取得
 */
export const getAnalyticsPerformance = (
  params: GetAnalyticsPerformanceParams,
  options?: SecondParameter<typeof getAnalyticsPerformanceMutator>,
  signal?: AbortSignal,
) => {
  return getAnalyticsPerformanceMutator<GetAnalyticsPerformance200>(
    { url: `/analytics/performance`, method: "GET", params, signal },
    options,
  );
};

export const getGetAnalyticsPerformanceQueryKey = (
  params: GetAnalyticsPerformanceParams,
) => {
  return [`/analytics/performance`, ...(params ? [params] : [])] as const;
};

export const getGetAnalyticsPerformanceInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getAnalyticsPerformance>>,
  TError = unknown,
>(
  params: GetAnalyticsPerformanceParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getAnalyticsPerformance>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getAnalyticsPerformanceMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAnalyticsPerformanceQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAnalyticsPerformance>>
  > = ({ signal }) => getAnalyticsPerformance(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAnalyticsPerformance>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAnalyticsPerformanceInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAnalyticsPerformance>>
>;
export type GetAnalyticsPerformanceInfiniteQueryError = unknown;

/**
 * @summary パフォーマンス分析データ取得
 */
export const useGetAnalyticsPerformanceInfinite = <
  TData = Awaited<ReturnType<typeof getAnalyticsPerformance>>,
  TError = unknown,
>(
  params: GetAnalyticsPerformanceParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getAnalyticsPerformance>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getAnalyticsPerformanceMutator>;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAnalyticsPerformanceInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetAnalyticsPerformanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getAnalyticsPerformance>>,
  TError = unknown,
>(
  params: GetAnalyticsPerformanceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAnalyticsPerformance>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getAnalyticsPerformanceMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAnalyticsPerformanceQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAnalyticsPerformance>>
  > = ({ signal }) => getAnalyticsPerformance(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAnalyticsPerformance>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAnalyticsPerformanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAnalyticsPerformance>>
>;
export type GetAnalyticsPerformanceQueryError = unknown;

/**
 * @summary パフォーマンス分析データ取得
 */
export const useGetAnalyticsPerformance = <
  TData = Awaited<ReturnType<typeof getAnalyticsPerformance>>,
  TError = unknown,
>(
  params: GetAnalyticsPerformanceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAnalyticsPerformance>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getAnalyticsPerformanceMutator>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAnalyticsPerformanceQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary 期間比較分析
 */
export const postAnalyticsComparison = (
  postAnalyticsComparisonBody: PostAnalyticsComparisonBody,
  options?: SecondParameter<typeof postAnalyticsComparisonMutator>,
) => {
  return postAnalyticsComparisonMutator<ComparisonResult>(
    {
      url: `/analytics/comparison`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAnalyticsComparisonBody,
    },
    options,
  );
};

export const getPostAnalyticsComparisonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAnalyticsComparison>>,
    TError,
    { data: PostAnalyticsComparisonBody },
    TContext
  >;
  request?: SecondParameter<typeof postAnalyticsComparisonMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAnalyticsComparison>>,
  TError,
  { data: PostAnalyticsComparisonBody },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAnalyticsComparison>>,
    { data: PostAnalyticsComparisonBody }
  > = (props) => {
    const { data } = props ?? {};

    return postAnalyticsComparison(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAnalyticsComparisonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAnalyticsComparison>>
>;
export type PostAnalyticsComparisonMutationBody = PostAnalyticsComparisonBody;
export type PostAnalyticsComparisonMutationError = unknown;

/**
 * @summary 期間比較分析
 */
export const usePostAnalyticsComparison = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAnalyticsComparison>>,
    TError,
    { data: PostAnalyticsComparisonBody },
    TContext
  >;
  request?: SecondParameter<typeof postAnalyticsComparisonMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAnalyticsComparison>>,
  TError,
  { data: PostAnalyticsComparisonBody },
  TContext
> => {
  const mutationOptions = getPostAnalyticsComparisonMutationOptions(options);

  return useMutation(mutationOptions);
};
